import React,{useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {AgendaSector,AgendaService,AgendaSlot,bookAgenda,loadAgendaServices,loadAgendaSlots} from './api';

const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const label=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'});
const clean=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

export function AgendaBooking({document,onBooked}:{document:string;onBooked:()=>Promise<void>}){
  const dates=useMemo(()=>Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return iso(d);}),[]);
  const [services,setServices]=useState<AgendaService[]>([]),[sectors,setSectors]=useState<AgendaSector[]>([]),[service,setService]=useState<AgendaService|null>(null);
  const [search,setSearch]=useState(''),[sector,setSector]=useState<number|null>(null);
  const [date,setDate]=useState(dates[0]!),[slots,setSlots]=useState<AgendaSlot[]>([]),[slot,setSlot]=useState<AgendaSlot|null>(null);
  const [cpf,setCpf]=useState(document),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{loadAgendaServices().then(v=>{setServices(v.servicos);setSectors(v.setores)}).catch(e=>setMessage(e.message));},[]);
  useEffect(()=>{if(!service)return;setBusy(true);setSlot(null);setMessage('');loadAgendaSlots(date,service.id).then(setSlots).catch(e=>{setSlots([]);setMessage(e.message)}).finally(()=>setBusy(false));},[date,service]);
  const confirm=async()=>{if(!service||!slot)return;setBusy(true);setMessage('');try{const r=await bookAgenda({serviceId:service.id,sectorId:service.setor_id,date,start:slot.inicio,document:cpf});setMessage(`✅ Agendamento ${r.protocolo} confirmado. A confirmação foi enviada ao seu WhatsApp.`);setSlot(null);await onBooked();}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível agendar.');}finally{setBusy(false)}};
  const ignored=new Set(['o','a','de','do','da','meu','minha','nao','esta','com','para','quero']);
  const terms=clean(search).split(/\s+/).filter(v=>v.length>1&&!ignored.has(v));
  const matches=(search.trim().length>=2||sector!==null)?services.filter(v=>(sector===null||v.setor_id===sector)&&(!terms.length||terms.some(t=>clean(v.nome).includes(t)))).slice(0,15):[];
  const choose=(value:AgendaService)=>{setService(value);setSearch(value.nome);setSector(value.setor_id);setMessage('')};
  return <View style={s.box}><Text style={s.title}>Agendar horário para orçamento</Text><Text style={s.help}>Escolha o serviço, a data e o horário. O profissional disponível será confirmado automaticamente.</Text>
    <Text style={s.label}>1. O QUE VOCÊ PRECISA?</Text><TextInput style={s.search} value={search} onChangeText={v=>{setSearch(v);setService(null)}} placeholder="Ex.: PS5 não liga, HDMI, limpeza..." placeholderTextColor="#687a72"/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}><Pressable style={[s.category,sector===null&&s.categoryOn]} onPress={()=>{setSector(null);setService(null)}}><Text style={[s.chipText,sector===null&&s.selectedText]}>Todos</Text></Pressable>{sectors.map(v=><Pressable key={v.id} style={[s.category,sector===v.id&&s.categoryOn]} onPress={()=>{setSector(v.id);setSearch('');setService(null)}}><Text style={[s.chipText,sector===v.id&&s.selectedText]}>{v.nome}</Text></Pressable>)}</ScrollView>
    {!service&&matches.length?<View style={s.results}>{matches.map(v=><Pressable key={v.id} style={s.result} onPress={()=>choose(v)}><View style={s.resultBody}><Text style={s.resultName}>{v.nome}</Text><Text style={s.resultMeta}>{v.duracao_min} min{Number(v.preco_brl)>0?` • a partir de R$ ${Number(v.preco_brl).toFixed(2).replace('.',',')}`:''}</Text></View><Text style={s.plus}>＋</Text></Pressable>)}</View>:null}
    {!service&&(search.trim().length>=2||sector!==null)&&!matches.length?<Text style={s.message}>Nenhum serviço encontrado. Tente outra palavra.</Text>:null}
    {service?<View style={s.chosen}><Text style={s.chosenLabel}>SERVIÇO ESCOLHIDO</Text><Text style={s.chosenName}>{service.nome}</Text><Pressable onPress={()=>{setService(null);setSearch('')}}><Text style={s.change}>Trocar</Text></Pressable></View>:null}
    {service?<><Text style={s.label}>2. DATA</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{dates.map(v=><Pressable key={v} style={[s.chip,date===v&&s.selected]} onPress={()=>setDate(v)}><Text style={[s.chipText,date===v&&s.selectedText]}>{label(v)}</Text></Pressable>)}</ScrollView></>:null}
    {service?<><Text style={s.label}>3. HORÁRIO</Text>{busy?<ActivityIndicator color="#53f6a7"/>:<View style={s.wrap}>{slots.filter(v=>!v.ocupado).map(v=><Pressable key={v.inicio} style={[s.time,slot?.inicio===v.inicio&&s.selected]} onPress={()=>setSlot(v)}><Text style={[s.chipText,slot?.inicio===v.inicio&&s.selectedText]}>{v.inicio}</Text></Pressable>)}</View>}</>:null}
    {slot?<><Text style={s.label}>4. CPF DO CLIENTE</Text><TextInput style={s.input} value={cpf} onChangeText={setCpf} keyboardType="numeric" placeholder="CPF para confirmar o agendamento" placeholderTextColor="#687a72"/><Pressable style={s.button} disabled={busy} onPress={confirm}>{busy?<ActivityIndicator color="#06110d"/>:<Text style={s.buttonText}>CONFIRMAR E RECEBER NO WHATSAPP</Text>}</Pressable></>:null}
    {message?<Text style={s.message}>{message}</Text>:null}
  </View>;
}
const s=StyleSheet.create({box:{backgroundColor:'#0b1914',borderWidth:1,borderColor:'#183c52',borderRadius:20,padding:17,gap:12},title:{color:'#fff',fontSize:19,fontWeight:'900'},help:{color:'#8c9c95',fontSize:12,lineHeight:18},label:{color:'#53f6a7',fontSize:10,fontWeight:'900',letterSpacing:1.3,marginTop:5},row:{gap:8},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},category:{borderWidth:1,borderColor:'#284039',borderRadius:20,paddingHorizontal:13,paddingVertical:8},categoryOn:{backgroundColor:'#53f6a7',borderColor:'#53f6a7'},chip:{borderWidth:1,borderColor:'#284039',borderRadius:12,paddingHorizontal:12,paddingVertical:9,maxWidth:230},time:{borderWidth:1,borderColor:'#284039',borderRadius:10,paddingHorizontal:14,paddingVertical:9},selected:{backgroundColor:'#53f6a7',borderColor:'#53f6a7'},chipText:{color:'#b6c3bd',fontSize:12,fontWeight:'700'},selectedText:{color:'#06110d'},search:{height:52,borderWidth:1,borderColor:'#315247',backgroundColor:'#10231c',borderRadius:13,paddingHorizontal:14,color:'#fff',fontSize:14},results:{borderWidth:1,borderColor:'#20372f',borderRadius:14,overflow:'hidden'},result:{minHeight:58,paddingHorizontal:13,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#1b3028',flexDirection:'row',alignItems:'center'},resultBody:{flex:1},resultName:{color:'#f2f6f4',fontSize:13,fontWeight:'800'},resultMeta:{color:'#71837a',fontSize:10,marginTop:3},plus:{color:'#53f6a7',fontSize:20},chosen:{backgroundColor:'#102a21',borderRadius:13,padding:13},chosenLabel:{color:'#53f6a7',fontSize:9,fontWeight:'900',letterSpacing:1},chosenName:{color:'#fff',fontSize:14,fontWeight:'800',marginTop:4},change:{color:'#8ebda9',fontSize:11,fontWeight:'800',marginTop:7},input:{height:50,borderWidth:1,borderColor:'#284039',borderRadius:12,paddingHorizontal:14,color:'#fff'},button:{height:52,backgroundColor:'#53f6a7',borderRadius:13,alignItems:'center',justifyContent:'center'},buttonText:{color:'#06110d',fontSize:11,fontWeight:'900',letterSpacing:.7},message:{color:'#dce7e2',fontSize:12,lineHeight:18}});
